# Generated by Django 4.0.6 on 2022-07-25 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipmentmodel_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
